export const FALLBACK_PASSAGE = {
    passage_id: 0,
    title: "1984 - Opening Passage",
    language: "en",
    difficulty: "medium",
    created_at: "2025-04-09T01:55:57.800Z",
    sentences: [
        {
            sentence_id: 1,
            passage_id: 0,
            text: "The hallway smelt of boiled cabbage and old rag mats.",
            completion_status: false,
            created_at: "2025-04-09T01:55:57.800Z",
        },
        {
            sentence_id: 2,
            passage_id: 0,
            text: "At one end of it a coloured poster, too large for indoor display, had been tacked to the wall.",
            completion_status: false,
            created_at: "2025-04-09T01:55:57.800Z",
        },
        {
            sentence_id: 3,
            passage_id: 0,
            text: "It depicted simply an enormous face, more than a metre wide: the face of a man of about forty-five, with a heavy black moustache and ruggedly handsome features.",
            completion_status: false,
            created_at: "2025-04-09T01:55:57.800Z",
        },
        {
            sentence_id: 4,
            passage_id: 0,
            text: "Winston made for the stairs.",
            completion_status: false,
            created_at: "2025-04-09T01:55:57.800Z",
        },
        {
            sentence_id: 5,
            passage_id: 0,
            text: "It was no use trying the lift.",
            completion_status: false,
            created_at: "2025-04-09T01:55:57.800Z",
        },
        {
            sentence_id: 6,
            passage_id: 0,
            text: "Even at the best of times it was seldom working, and at present the electric current was cut off during daylight hours.",
            completion_status: false,
            created_at: "2025-04-09T01:55:57.800Z",
        },
        {
            sentence_id: 7,
            passage_id: 0,
            text: "It was part of the economy drive in preparation for Hate Week.",
            completion_status: false,
            created_at: "2025-04-09T01:55:57.800Z",
        },
        {
            sentence_id: 8,
            passage_id: 0,
            text: "The flat was seven flights up, and Winston, who was thirty-nine and had a varicose ulcer above his right ankle, went slowly, resting several times on the way.",
            completion_status: false,
            created_at: "2025-04-09T01:55:57.800Z",
        },
        {
            sentence_id: 9,
            passage_id: 0,
            text: "On each landing, opposite the lift-shaft, the poster with the enormous face gazed from the wall.",
            completion_status: false,
            created_at: "2025-04-09T01:55:57.800Z",
        },
        {
            sentence_id: 10,
            passage_id: 0,
            text: "It was one of those pictures which are so contrived that the eyes follow you about when you move.",
            completion_status: false,
            created_at: "2025-04-09T01:55:57.800Z",
        },
        {
            sentence_id: 11,
            passage_id: 0,
            text: "BIG BROTHER IS WATCHING YOU, the caption beneath it ran.",
            completion_status: false,
            created_at: "2025-04-09T01:55:57.800Z",
        },
    ],
};
