name: Enforce PR Title

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  enforce-pr-title:
    name: Enforce PR Title
    runs-on: ubuntu-latest
    steps:
    - uses: deepakputhraya/action-pr-title@master
      with:
        regex: '^[A-Z]+-[0-9]+: [A-Z].+'
